### ISSUE TITLE
avoid error by reprojecting all data to EPSG:4326 within function

### ISSUE THREAD

**Issue by annescharf** [alexvmt/animal-movement-summary-and-stationarity-analysis#11]
Hi @alexvmt & @mb-feldm,
it seems your app needs the data to be in a geographic coordinate system, i.e. EPSG:4326. Given that the error that it gives is not at all intuitive, I would recommend to include in the function checking if the incoming data is in lat/long (there are several packages that do that, I think), and if not to reprojected to EPSG:4326  and print a message (e.g. logger.info()) to let the user know that the data were reprojected. Maybe just implement it when transitioning the app to move2. Also make a note of this in the documentation.
Best, Anne

**Comment by alexvmt** [comment]
Hi @annescharf,
Thanks! We'll add this to our backlog and hope to deal with it soon.
Best,
Alex

**Comment by alexvmt** [comment]
@annescharf, we fixed the issue ([this commit](https://github.com/alexvmt/animal-movement-summary-and-stationarity-analysis/pull/16/commits/64b9410ad797397532e0fecf86c4625517dcdb3c)).
