### ISSUE TITLE
error by user

### ISSUE THREAD

**Issue by andreakoelzsch** [alexvmt/animal-movement-summary-and-stationarity-analysis#18]
Hi @alexvmt 
We had a message from Greer Smith, who is using your on a regular basis, but gets an error since we have updated the Movebank App to move2. Please, can you have a look into it? Might also be a good time to start with a transition to move2 for this App. Thanks! Details below. Best, Andrea

message from Greer: "When do you think the app "Animal Movement Summary and Stationarity Analysis" will be back operational? Since the updates, I have had this error message. "Error Replacement has 0 Rows, data has 8380." and of course the data number changes to however many data points i am trying to analyze." Screenshots from him below

![Screenshot (343)](https://github.com/alexvmt/animal-movement-summary-and-stationarity-analysis/assets/65662928/a77f4419-3ebc-44df-a0dd-7f32698ae6d1)
![Screenshot (342)](https://github.com/alexvmt/animal-movement-summary-and-stationarity-analysis/assets/65662928/68b890f2-ade3-41e6-ba5c-c31e0335966b)

**Comment by alexvmt** [comment]
Hi @andreakoelzsch,
Thanks for the info! Greer has reached out to me, too. We're currently sorting things out.
I think the issue could be indeed that our app still takes regular move objects as input and not move2 objects.
I also just released a major update of our current app. When everything goes well this will be the base for a new app using move2, deprecating the current one. We hope to get that done soon.
Best,
Alex

**Comment by andreakoelzsch** [comment]
Thanks!

**Comment by andreakoelzsch** [comment]
Hi @alexvmt, I have updated the new Movebank App. The workflow that you had shared with me, runs now and I hope that the one above is also back functioning. Please let me know, if not. Thanks for all the work! Frohe Weihnachten!
