### ISSUE TITLE
thanks and comments from MoveApps

### ISSUE THREAD

**Issue by andreakoelzsch** [alexvmt/animal-movement-summary-and-stationarity-analysis#8]
Hi Alex,
Thanks so much for your contribution to MoveApps and EMAC23!

I have built your App so that you can test it on MoveApps. The App runs for me locally fine and looks very good, but there are three changes I would receommend:

1) The two lines 19-21 in ShinyModule.R are outside of the functions, which is not meant to be, but we are not sure if it could work. I would recomemend to move them e.g. to line 280, but try if/how it works in MoveApps. In case it does not work, the error message should be clear.
2) Locally the App did only work when I added the command "library(shiny)", might be worth to explicitly add it to the ShinyModule.R top and also the dependencies in the appspec.json. (even if it locally gets loaded as a dependency of shinybusy)
3) Please, indicate in the readme.md that the output data type is moveStack (UI is not really an output type any more), i.e. the input data so that the App can be integrated in a workflow.

All the best, Andrea
(@annescharf FYI)

**Comment by alexvmt** [comment]
Hi @andreakoelzsch,

Thanks a lot for your feedback! I implemented all your points. I just need to do a new release and update the version on MoveApps. Before I do that though, I have a question myself. I tested the app on MoveApps and everything seems to work fine. However, I noticed an error message (see screenshot). It doesn't seem to appear when testing the app locally. I'm not sure why it happens and it doesn't seem to have any effects on the app's functionality (I'm not entirely sure of course). It seems like it might have to do with the data object that is loaded (moveStack) and made reactive. Do you perhaps have any ideas on what might be going on?

Best,
Alex

@mb-feldm fyi

![error](https://github.com/alexvmt/animal-movement-summary-and-stationarity-analysis/assets/36922158/f98d858d-bf14-487b-b003-f06200b02713)

**Comment by andreakoelzsch** [comment]
Hi @alexvmt, thanks for the changes and your question. The error that you see has to do with some internal configuration storing that is not working correctly, yet. We are about to rework the system and all Apps in the coming weeks, I will put this on the list of things to fix. Best, Andrea

**Comment by alexvmt** [comment]
Hi @andreakoelzsch,
Alright, thanks for letting us know. I just released a new version of our app with your feedback implemented and also submitted a new version on MoveApps. I'll test it there again once it's been built.
Best,
Alex

**Comment by andreakoelzsch** [comment]
@alexvmt new App version built. thanks!
